### Data Science using Python

In [4]:
#Estrutura de Dicionário
dict_morse = {".-": "A", "-...": "B", "-.-.": "C", "-..": "D", ".": "E", "..-.": "F","--.": "G", "....": "H", "..": "I", ".---": "J", "-.-": "K", ".-..": "L","--": "M", "-.": "N", "---": "O", ".--.": "P", "--.-": "Q", ".-.": "R","...": "S", "-": "T", "..-": "U", "...-": "V", ".--": "W", "-..-": "X","-.--": "Y", "--..": "Z", "-----": 0, ".----": 1, "..---": 2, "...--": 3,"....-": 4, ".....": 5, "-....": 6, "--...": 7, "---..": 8, "----.": 9}

In [5]:
#visualizando Dicionário
print(dict_morse)

{'.-': 'A', '-...': 'B', '-.-.': 'C', '-..': 'D', '.': 'E', '..-.': 'F', '--.': 'G', '....': 'H', '..': 'I', '.---': 'J', '-.-': 'K', '.-..': 'L', '--': 'M', '-.': 'N', '---': 'O', '.--.': 'P', '--.-': 'Q', '.-.': 'R', '...': 'S', '-': 'T', '..-': 'U', '...-': 'V', '.--': 'W', '-..-': 'X', '-.--': 'Y', '--..': 'Z', '-----': 0, '.----': 1, '..---': 2, '...--': 3, '....-': 4, '.....': 5, '-....': 6, '--...': 7, '---..': 8, '----.': 9}


In [6]:
#Com Dcionários podemos visualizar ITEMS, CHAVES E VALORES
print(dict_morse.items())
print(dict_morse.keys())
print(dict_morse.values())

dict_items([('.-', 'A'), ('-...', 'B'), ('-.-.', 'C'), ('-..', 'D'), ('.', 'E'), ('..-.', 'F'), ('--.', 'G'), ('....', 'H'), ('..', 'I'), ('.---', 'J'), ('-.-', 'K'), ('.-..', 'L'), ('--', 'M'), ('-.', 'N'), ('---', 'O'), ('.--.', 'P'), ('--.-', 'Q'), ('.-.', 'R'), ('...', 'S'), ('-', 'T'), ('..-', 'U'), ('...-', 'V'), ('.--', 'W'), ('-..-', 'X'), ('-.--', 'Y'), ('--..', 'Z'), ('-----', 0), ('.----', 1), ('..---', 2), ('...--', 3), ('....-', 4), ('.....', 5), ('-....', 6), ('--...', 7), ('---..', 8), ('----.', 9)])
dict_keys(['.-', '-...', '-.-.', '-..', '.', '..-.', '--.', '....', '..', '.---', '-.-', '.-..', '--', '-.', '---', '.--.', '--.-', '.-.', '...', '-', '..-', '...-', '.--', '-..-', '-.--', '--..', '-----', '.----', '..---', '...--', '....-', '.....', '-....', '--...', '---..', '----.'])
dict_values(['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z', 0, 1, 2, 3, 4, 5, 6, 7, 8, 9])


In [7]:
#Conferindo o tipo
type(dict_morse.values())

dict_values

In [8]:
type(dict_morse)

dict

In [9]:
#Para conferir tamanhos utilizamos a função LEN
print(len(dict_morse))
print(len(dict_morse.values()))

36
36


### Acessando e Manipulando dados

In [10]:
#Podemos acessar valores através de chaves
dict_morse['.-']

'A'

In [11]:
type(dict_morse['.-'])

str

In [13]:
type(dict_morse["..---"])
print(dict_morse["..---"])

2


In [14]:
dict_morse.get("..---")

2

### Operações

In [16]:
#Imprimindo chaves de um dicionário
dict_morse.keys()

dict_keys(['.-', '-...', '-.-.', '-..', '.', '..-.', '--.', '....', '..', '.---', '-.-', '.-..', '--', '-.', '---', '.--.', '--.-', '.-.', '...', '-', '..-', '...-', '.--', '-..-', '-.--', '--..', '-----', '.----', '..---', '...--', '....-', '.....', '-....', '--...', '---..', '----.'])

In [18]:
for key in dict_morse:
    print(f"Chave: {key}, valor : {dict_morse[key]}")

Chave: .-, valor : A
Chave: -..., valor : B
Chave: -.-., valor : C
Chave: -.., valor : D
Chave: ., valor : E
Chave: ..-., valor : F
Chave: --., valor : G
Chave: ...., valor : H
Chave: .., valor : I
Chave: .---, valor : J
Chave: -.-, valor : K
Chave: .-.., valor : L
Chave: --, valor : M
Chave: -., valor : N
Chave: ---, valor : O
Chave: .--., valor : P
Chave: --.-, valor : Q
Chave: .-., valor : R
Chave: ..., valor : S
Chave: -, valor : T
Chave: ..-, valor : U
Chave: ...-, valor : V
Chave: .--, valor : W
Chave: -..-, valor : X
Chave: -.--, valor : Y
Chave: --.., valor : Z
Chave: -----, valor : 0
Chave: .----, valor : 1
Chave: ..---, valor : 2
Chave: ...--, valor : 3
Chave: ....-, valor : 4
Chave: ....., valor : 5
Chave: -...., valor : 6
Chave: --..., valor : 7
Chave: ---.., valor : 8
Chave: ----., valor : 9


In [31]:
# Adicionando
dict_morse["teste"] = 32

In [32]:
print(dict_morse)

{'.-': 'a', '-...': 'B', '-.-.': 'C', '-..': 'D', '.': 'E', '..-.': 'F', '--.': 'G', '....': 'H', '..': 'I', '.---': 'J', '-.-': 'K', '.-..': 'L', '--': 'M', '-.': 'N', '---': 'O', '.--.': 'P', '--.-': 'Q', '.-.': 'R', '...': 'S', '-': 'T', '..-': 'U', '...-': 'V', '.--': 'W', '-..-': 'X', '-.--': 'Y', '--..': 'Z', '-----': 0, '.----': 1, '..---': 2, '...--': 3, '....-': 4, '.....': 5, '-....': 6, '--...': 7, '---..': 8, '----.': 9, 'teste': 32}


In [33]:
# Removendo itens
dict_morse.pop("teste")
print(dict_morse)

{'.-': 'a', '-...': 'B', '-.-.': 'C', '-..': 'D', '.': 'E', '..-.': 'F', '--.': 'G', '....': 'H', '..': 'I', '.---': 'J', '-.-': 'K', '.-..': 'L', '--': 'M', '-.': 'N', '---': 'O', '.--.': 'P', '--.-': 'Q', '.-.': 'R', '...': 'S', '-': 'T', '..-': 'U', '...-': 'V', '.--': 'W', '-..-': 'X', '-.--': 'Y', '--..': 'Z', '-----': 0, '.----': 1, '..---': 2, '...--': 3, '....-': 4, '.....': 5, '-....': 6, '--...': 7, '---..': 8, '----.': 9}


In [34]:
# Alterando Valores de um dicionário
dict_morse['.-'] = 'a'

### Listas

In [37]:
lst_values = list(dict_morse.values())
print(lst_values)

['a', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z', 0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


### Acessando e Manipulando Dados

In [41]:
#lista[indice]
#lista[inicio:parada]
print(
    f"{lst_values[0]} \n",
    f"{lst_values[0:5]} \n",
    f"{lst_values[-1]} \n"
    f"{type(lst_values[-1])}"
)

a 
 ['a', 'B', 'C', 'D', 'E'] 
 9 
<class 'int'>


In [42]:
# lista [inicio:parada:passo]
lst_values[0:10:2]

['a', 'C', 'E', 'G', 'I']

### Operações

In [43]:
# Concatenação
lst_values[:5] + lst_values[-3:]

['a', 'B', 'C', 'D', 'E', 7, 8, 9]

In [45]:
#alterando elementos
lst_values[0] = "G"
lst_values[0]
lst_values[0] = "A"
lst_values[0]

'A'

In [50]:
# Adcionando elementos a lista
lst_values.append(12)
print(lst_values)

['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z', 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 'olá', 'olá', 12, 12, 12]


In [54]:
#Encontrando a posição de um elemento e removendo
lst_values.pop(37)
print(lst_values)
lst_values.remove("olá")
print(lst_values)

['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z', 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 'olá']
['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z', 0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


In [55]:
# Outra forma de remover elementos da lista
lst = ['A', 'B', 'C', 'D', 'E', 7, 8, 9]
lst.clear()
lst

[]

In [56]:
# Multidimensionalidade
mult_lst = [lst_values[:5], lst_values[-5:]]
mult_lst

[['A', 'B', 'C', 'D', 'E'], [5, 6, 7, 8, 9]]

In [57]:
mult_lst[0]

['A', 'B', 'C', 'D', 'E']

### Funções Importantes COUNT, SUM, SORT

In [59]:
# count
lst = ['A', 'B', 'C', 'D', 'E', 7, 8, 9, 'A','A', 7]
print(lst.count(7))
print(lst.count('A'))
print(lst.count('C'))

2
3
1


In [60]:
# Sum
sum([1,2,3])

6

In [61]:
# sort
sorted([1,9,2,5,3,12])

[1, 2, 3, 5, 9, 12]

In [62]:
txt = "Carlos"
txt[0]

'C'

In [63]:
txt[0] = "M"
txt

TypeError: 'str' object does not support item assignment

### ARRAYS

In [64]:
import array
import numpy as np

In [65]:
arr = array.array('i', [1,2,3])

In [68]:
arr[0]

1

In [69]:
print([5,10,15]*2)

[5, 10, 15, 5, 10, 15]


#### NUMPY - OPERAÇÕES MATEMÁTICAS

In [70]:
# SOMA DE ARRAYS
arr1 = np.array([5,10,15])
arr2 = np.array([2,5,10])
print(arr1 + arr2)

[ 7 15 25]


In [72]:
print(arr1 - arr2)
print(arr1 * arr2)

[3 5 5]
[ 10  50 150]


#### List Comprehension

In [73]:
values = [-5, 7, 1, 0, 10, 100, 33, 2]

In [75]:
quadrados = []
for v in values:
    quadrados.append(v**2)
print(quadrados)

[25, 49, 1, 0, 100, 10000, 1089, 4]


In [76]:
# Com list comprehesion
[v**2 for v in values]

[25, 49, 1, 0, 100, 10000, 1089, 4]

In [77]:
import time

In [80]:
# Comparando a performance listas e np arrays

a = time.time()
L = range(1000000)
[i**2 for i in L]
print(time.time() - a)

a = time.time()
b = np.arange(1000000)
b**2
print(time.time() - a)

0.14519906044006348
0.015041589736938477


#### Tuplas

In [81]:
tuple_values = tuple(lst_values)
print(tuple_values)

('A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z', 0, 1, 2, 3, 4, 5, 6, 7, 8, 9)


In [82]:
type(tuple_values) 

tuple

In [83]:
# Acessando dados
print(tuple_values[0:2])
print(tuple_values[-1]) 

('A', 'B')
9


In [84]:
# Operações
print((1,2) + (3,4))

(1, 2, 3, 4)


In [85]:
import timeit

lista_teste = timeit.timeit(stmt='[1,2,3,4,5]', number=1_000_000)
tupla_teste = timeit.timeit(stmt='(1,2,3,4,5)', number=1_000_000)
print(f'Tempo da lista: {lista_teste}') 
print(f'Tempo da tupla: {tupla_teste}')

Tempo da lista: 0.0896078999794554
Tempo da tupla: 0.019953100010752678


#### Conjuntos

In [86]:
cj = set('cachorro')
cj

{'a', 'c', 'h', 'o', 'r'}

In [87]:
type(cj)

set

In [88]:
# criando set a partir de uma lista
set(list('cachorro'))

{'a', 'c', 'h', 'o', 'r'}

#### Acessando e manipulando dados

In [89]:
len("cachorro")
len(cj)

5

In [90]:
cj.add("2")
print(cj)
cj.discard("2")
print(cj)

{'o', 'h', 'r', 'c', '2', 'a'}
{'o', 'h', 'r', 'c', 'a'}


#### Operações

In [93]:
alfabeto = {'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J',
    'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T',
    'U','V', 'W', 'X', 'Y', 'Z'}
set_values = set(dict_morse.values())

In [94]:
# Interseção
print(set_values & alfabeto)
print(set_values.intersection(alfabeto))

{'E', 'B', 'C', 'X', 'J', 'H', 'S', 'T', 'L', 'N', 'R', 'D', 'Z', 'M', 'K', 'I', 'G', 'Q', 'W', 'U', 'O', 'Y', 'P', 'V', 'F'}
{'E', 'B', 'C', 'X', 'J', 'H', 'S', 'T', 'L', 'N', 'R', 'D', 'Z', 'M', 'K', 'I', 'G', 'Q', 'W', 'U', 'O', 'Y', 'P', 'V', 'F'}


In [95]:
#Diferença
print(set_values  - alfabeto) 
print(set_values.difference(alfabeto)) 
print(alfabeto - set_values) 
print(alfabeto.difference(set_values))

{0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 'a'}
{0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 'a'}
{'A'}
{'A'}


In [96]:
# Diferença simétrica
print(set_values.symmetric_difference(alfabeto))
print(alfabeto.symmetric_difference(set_values))
print(set_values ^ alfabeto)
print(alfabeto ^ set_values)

{0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 'a', 'A'}
{0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 'A', 'a'}
{0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 'a', 'A'}
{0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 'A', 'a'}


In [97]:
# união
print({"cc", "xx"}| alfabeto) 
print({"cc", "xx"}.union(alfabeto))

{'E', 'B', 'Z', 'xx', 'M', 'K', 'C', 'X', 'I', 'G', 'Q', 'W', 'F', 'J', 'H', 'U', 'O', 'A', 'Y', 'S', 'P', 'T', 'L', 'N', 'R', 'V', 'cc', 'D'}
{'E', 'B', 'Z', 'xx', 'M', 'K', 'C', 'X', 'I', 'G', 'Q', 'W', 'F', 'J', 'H', 'U', 'O', 'A', 'Y', 'S', 'P', 'T', 'L', 'N', 'R', 'V', 'cc', 'D'}


#### Resumo

- Listas: Coleção ordenada e mutável. Permite membros duplicados.
- Tuplas: Coleção ordenada e imutável. Permite membros duplicados.
- Sets: Coleção não-ordenada e não-indexada. Não permite membros duplicados.
- Dicionários: Coleção não-ordenada, mutável e indexável. Não permite membros duplicados.